fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\Usuario
  group:
    group_class: App\Entity\Grupo
    group_manager: sonata.user.orm.group_manager
  service:
    user_manager: sonata.user.orm.user_manager
  from_email:
    address: administracao@uft.edu.br
    sender_name: "Administração"